In [1225]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import scipy.special as special
import scipy.optimize as optimize
import seaborn as sns
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [1226]:
df = pd.read_csv('Paris_50_Columnas.csv')
df.head(2)

C:\Users\joker\AppData\Local\Temp\ipykernel_11672\4219480268.py:1: DtypeWarning: Columns (12,13) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('Paris_50_Columnas.csv')


Unnamed: 0    id                        listing_url last_scraped  \
0           0  3109  https://www.airbnb.com/rooms/3109   2024-09-11   
1           1  5396  https://www.airbnb.com/rooms/5396   2024-09-13   

                                         description  host_id  \
0  Lovely Appartment with one bedroom with a Quee...     3631   
1  NEW SOFA-BED SINCE JUNE 2023, Please disregard...     7903   

                                 host_url  host_since host_response_time  \
0  https://www.airbnb.com/users/show/3631  2008-10-14     within an hour   
1  https://www.airbnb.com/users/show/7903  2009-02-14     within an hour   

  host_response_rate  ... review_scores_checkin review_scores_communication  \
0                NaN  ...                  5.00                        5.00   
1               100%  ...                  4.81                        4.84   

  review_scores_location        license instant_bookable  \
0                   5.00  7511409139079                t   
1                   4.96  7510402838018                f   

  calculated_host_listings_count calculated_host_listings_count_entire_homes  \
0                              1                                           1   
1                              1                                           1   

  calculated_host_listings_count_private_rooms  \
0                                            0   
1                                            0   

  calculated_host_listings_count_shared_rooms reviews_per_month  
0                                           0              0.05  
1                                           0              2.23  

[2 rows x 51 columns]

**Regresión logistica "host is superhost"**

In [1227]:
df[["price", "host_total_listings_count", "review_scores_communication"]].apply(pd.to_numeric, errors="coerce").isna().sum()


price                          0
host_total_listings_count      6
review_scores_communication    0
dtype: int64

In [1228]:
df["host_total_listings_count"] = pd.to_numeric(df["host_total_listings_count"].replace("No Hay", 0))


In [1229]:
df[["price", "host_total_listings_count", "review_scores_communication"]].apply(pd.to_numeric, errors="coerce").isna().sum()


price                          0
host_total_listings_count      0
review_scores_communication    0
dtype: int64

In [1230]:
Vars_Indep = df[['price','host_total_listings_count','review_scores_communication']]
Var_dep = df['host_is_superhost']

In [1231]:
X = Vars_Indep
Y = Var_dep

In [1232]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.3, random_state=None)

In [1233]:
escalar = StandardScaler()

In [1234]:
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

In [1235]:
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression(class_weight='balanced')
algoritmo.fit(X_train, y_train)

LogisticRegression(class_weight='balanced')

In [1236]:
y_pred = algoritmo.predict(X_test)
y_pred

array(['t', 'f', 't', ..., 't', 't', 'f'], dtype=object)

In [1237]:
#Matriz de confusión
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred)
print(matriz)

[[13570  9810]
 [ 1474  3785]]


In [1238]:
from sklearn.metrics import precision_score
precision = precision_score(y_test, y_pred, average="binary", pos_label="f")
print('precision: ',precision)

precision:  0.9020207391651157


In [1239]:
from sklearn.metrics import accuracy_score
exactitud = accuracy_score(y_test, y_pred)  
print("exatitud: ",exactitud)

exatitud:  0.6059918293236496


In [1240]:
from sklearn.metrics import recall_score
sensibilidad = recall_score(y_test, y_pred, average="binary", pos_label="f")
print("Sensibilidad del modelo:")
print("sensibilidad: ",sensibilidad)

Sensibilidad del modelo:
sensibilidad:  0.5804106073567151


**Regresión logistica "instant_bookable"**

In [1241]:
unico = np.unique(df['instant_bookable'])
unico

array(['f', 't'], dtype=object)

In [1242]:
Vars_Indep = df[['number_of_reviews','host_total_listings_count','review_scores_checkin']]
Var_dep = df['instant_bookable']

In [1243]:
X = Vars_Indep
Y = Var_dep

In [1244]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.3, random_state=None)

In [1245]:
escalar = StandardScaler()

In [1246]:
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

In [1247]:
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression()
algoritmo.fit(X_train, y_train)

LogisticRegression()

In [1248]:
y_pred = algoritmo.predict(X_test)
y_pred

array(['f', 'f', 'f', ..., 'f', 'f', 'f'], dtype=object)

In [1249]:
#Matriz de confusión
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred)
print(matriz)

[[21136   428]
 [ 6255   820]]


In [1250]:
from sklearn.metrics import precision_score
precision = precision_score(y_test, y_pred, average="binary", pos_label="f")
print('precision: ',precision)

precision:  0.7716403198130772


In [1251]:
from sklearn.metrics import accuracy_score
exactitud = accuracy_score(y_test, y_pred)  
print("exatitud: ",exactitud)

exatitud:  0.7666468801284961


In [1252]:
from sklearn.metrics import recall_score
sensibilidad = recall_score(y_test, y_pred, average="binary", pos_label="f")
print("sensibilidad: ",sensibilidad)

sensibilidad:  0.9801521053607865


**Regresión logistica "host_response_time"**

In [1253]:
unico = np.unique(df['host_response_time'])
unico

array(['a few days or more', 'within a day', 'within a few hours',
       'within an hour'], dtype=object)

In [1254]:
df['host_response_time'] = df['host_response_time'].replace(['a few days or more','within a day', 'within a few hours'],'NO within an hour')

In [1255]:
Vars_Indep = df[['number_of_reviews','host_total_listings_count','review_scores_communication']]
Var_dep = df['host_response_time']

In [1256]:
X = Vars_Indep
Y = Var_dep
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.3, random_state=None)
escalar = StandardScaler()

In [1257]:
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

In [1258]:
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression()
algoritmo.fit(X_train, y_train)

LogisticRegression()

In [1259]:
y_pred = algoritmo.predict(X_test)
y_pred

array(['within an hour', 'within an hour', 'within an hour', ...,
       'within an hour', 'within an hour', 'within an hour'], dtype=object)

In [1260]:
#Matriz de confusión
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred)
print(matriz)

[[    0  5933]
 [    5 22701]]


In [1261]:
from sklearn.metrics import precision_score
precision = precision_score(y_test, y_pred, average="binary", pos_label="within an hour")
print('precision: ',precision)

precision:  0.7927987706921841


In [1262]:
from sklearn.metrics import accuracy_score
exactitud = accuracy_score(y_test, y_pred)  
print("exatitud: ",exactitud)

exatitud:  0.7926603582527323


In [1263]:
from sklearn.metrics import recall_score
sensibilidad = recall_score(y_test, y_pred, average="binary", pos_label="within an hour")
print("sensibilidad: ",sensibilidad)

sensibilidad:  0.9997797938870783


**Regresión logistica "room_type"**

In [1264]:
unico = np.unique(df['room_type'])
unico

array(['Entire home/apt', 'Hotel room', 'Private room', 'Shared room'],
      dtype=object)

In [1265]:
df['room_type'] = df['room_type'].replace(['Entire home/apt','Hotel room', 'Shared room'],'NO Private room')

In [1266]:
Vars_Indep = df[['bedrooms','price','beds']]
Var_dep = df['room_type']

In [1267]:
X = Vars_Indep
Y = Var_dep
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.3, random_state=None)
escalar = StandardScaler()

In [1268]:
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

In [1269]:
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression(class_weight='balanced')
algoritmo.fit(X_train, y_train)

LogisticRegression(class_weight='balanced')

In [1270]:
y_pred = algoritmo.predict(X_test)
y_pred

array(['NO Private room', 'Private room', 'Private room', ...,
       'NO Private room', 'Private room', 'Private room'], dtype=object)

In [1271]:
#Matriz de confusión
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred)
print(matriz)

[[17217  8699]
 [ 1467  1256]]


In [1272]:
from sklearn.metrics import precision_score
precision = precision_score(y_test, y_pred, average="binary", pos_label="Private room")
print('precision: ',precision)

precision:  0.12616775489703666


In [1273]:
from sklearn.metrics import accuracy_score
exactitud = accuracy_score(y_test, y_pred)  
print("exatitud: ",exactitud)

exatitud:  0.6450295052201543


In [1274]:
from sklearn.metrics import recall_score
sensibilidad = recall_score(y_test, y_pred, average="binary", pos_label="Private room")
print("sensibilidad: ",sensibilidad)

sensibilidad:  0.4612559676827029


**Regresión logistica "review_scores cleanliness"**

In [1275]:
# 1. Eliminar filas con valores nulos en la variable objetivo
df = df.dropna(subset=['review_scores_cleanliness'])

In [1276]:
# 2. Crear variable binaria: 1 si limpieza >= 4.8, 0 si < 4.8
df['cleanliness_binaria'] = df['review_scores_cleanliness'].apply(lambda x: 1 if x >= 4.8 else 0).astype(int)

In [1277]:
# 3. Definir variables independientes y dependiente
Vars_Indep = df[['room_type','price','host_is_superhost']]
Var_dep = df['cleanliness_binaria']  # ¡¡¡Esto es CLAVE!!!

In [1278]:
# 4. One-hot encoding
X = pd.get_dummies(Vars_Indep, drop_first=True)

In [1279]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Var_dep, test_size=0.3, random_state=42)

In [1280]:
escalar = StandardScaler()

In [1281]:
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

In [1282]:
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression(class_weight='balanced')
algoritmo.fit(X_train, y_train)

LogisticRegression(class_weight='balanced')

In [1283]:
y_pred = algoritmo.predict(X_test)
y_pred

array([0, 1, 0, ..., 0, 0, 0])

In [1284]:
#Matriz de confusión
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred)
print(matriz)

[[16211  2301]
 [ 7083  3044]]


In [1285]:
from sklearn.metrics import precision_score
precision = precision_score(y_test, y_pred, average="binary", pos_label=1)
print('precision: ',precision)

precision:  0.5695042095416277


In [1286]:
from sklearn.metrics import accuracy_score
exactitud = accuracy_score(y_test, y_pred)  
print("exactitud: ",exactitud)

exactitud:  0.6723349278955271


In [1287]:
from sklearn.metrics import recall_score
sensibilidad = recall_score(y_test, y_pred, average="binary", pos_label=1)
print("Sensibilidad del modelo:")
print("sensibilidad: ",sensibilidad)

Sensibilidad del modelo:
sensibilidad:  0.30058260096771006


**Regresión logistica "host_identity_verified"**

In [1288]:
# Reemplazar 'No Hay' por 0 en las variables independientes
vars_indep_cols = ['price', 'number_of_reviews', 'review_scores_communication']
df[vars_indep_cols] = df[vars_indep_cols].replace('No Hay', 0)

# Reemplazar 'No Hay' por 'f' en la variable dependiente
df['host_identity_verified'] = df['host_identity_verified'].replace('No Hay', 'f')

# Convertir a tipo numérico las independientes
df[vars_indep_cols] = df[vars_indep_cols].apply(pd.to_numeric)

# Finalmente, asignar X e Y
X = df[vars_indep_cols]
Y = df['host_identity_verified']


In [1289]:
#Matriz de confusión
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred)
print(matriz)

[[16211  2301]
 [ 7083  3044]]


In [1290]:
Vars_Indep = df[['price','number_of_reviews','review_scores_communication']]
Var_dep = df['host_identity_verified']

In [1291]:
df[df['host_identity_verified'] == 'No Hay']


Empty DataFrame
Columns: [Unnamed: 0, id, listing_url, last_scraped, description, host_id, host_url, host_since, host_response_time, host_response_rate, host_acceptance_rate, host_is_superhost, host_listings_count, host_total_listings_count, host_verifications, host_identity_verified, neighbourhood, neighbourhood_cleansed, property_type, room_type, accommodates, bathrooms, bedrooms, beds, amenities, price, minimum_nights, maximum_nights, has_availability, availability_30, availability_60, availability_90, availability_365, calendar_last_scraped, number_of_reviews, number_of_reviews_ltm, number_of_reviews_l30d, first_review, last_review, review_scores_accuracy, review_scores_cleanliness, review_scores_checkin, review_scores_communication, review_scores_location, license, instant_bookable, calculated_host_listings_count, calculated_host_listings_count_entire_homes, calculated_host_listings_count_private_rooms, calculated_host_listings_count_shared_rooms, reviews_per_month, cleanliness_binaria]
Index: []

[0 rows x 52 columns]

In [1292]:
X = Vars_Indep
Y = Var_dep

In [1293]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.3, random_state=None)

In [1294]:
escalar = StandardScaler()

In [1295]:
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

In [1296]:
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression(class_weight='balanced')
algoritmo.fit(X_train, y_train)

LogisticRegression(class_weight='balanced')

In [1297]:
y_pred = algoritmo.predict(X_test)
y_pred

array(['f', 'f', 't', ..., 't', 't', 'f'], dtype=object)

In [1298]:
#Matriz de confusión
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred)
print(matriz)

[[ 2316   475]
 [17372  8476]]


In [1299]:
from sklearn.metrics import precision_score
precision = precision_score(y_test, y_pred, average="binary", pos_label="f")
print('precision: ',precision)

precision:  0.11763510767980495


In [1300]:
from sklearn.metrics import accuracy_score
exactitud = accuracy_score(y_test, y_pred)  
print("exatitud: ",exactitud)

exatitud:  0.37682879988826423


In [1301]:
from sklearn.metrics import recall_score
sensibilidad = recall_score(y_test, y_pred, average="binary", pos_label="f")
print("Sensibilidad del modelo:")
print("sensibilidad: ",sensibilidad)

Sensibilidad del modelo:
sensibilidad:  0.8298101039054102


**Regresión logistica "has_availability"**

In [1302]:
Vars_Indep = df[['number_of_reviews','host_total_listings_count','review_scores_checkin']]
Var_dep = df['has_availability']

In [1303]:
X = Vars_Indep
Y = Var_dep

In [1304]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.3, random_state=None)

In [1305]:
escalar = StandardScaler()

In [1306]:
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

In [1307]:
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression(class_weight='balanced')
algoritmo.fit(X_train, y_train)

LogisticRegression(class_weight='balanced')

In [1308]:
y_pred = algoritmo.predict(X_test)
y_pred

array(['f', 'f', 't', ..., 't', 't', 't'], dtype=object)

In [1309]:
#Matriz de confusión
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred)
print(matriz)

[[ 1394   146]
 [12783 14316]]


In [1310]:
from sklearn.metrics import precision_score
precision = precision_score(y_test, y_pred, average="binary", pos_label="f")
print('precision: ',precision)

precision:  0.09832827819707977


In [1311]:
from sklearn.metrics import accuracy_score
exactitud = accuracy_score(y_test, y_pred)  
print("exactitud: ",exactitud)

exactitud:  0.548552672928524


In [1312]:
from sklearn.metrics import recall_score
sensibilidad = recall_score(y_test, y_pred, average="binary", pos_label="f")
print("Sensibilidad del modelo:")
print("sensibilidad: ",sensibilidad)

Sensibilidad del modelo:
sensibilidad:  0.9051948051948052


**Regresión logistica "review_scores_communication"**

In [1313]:
# 1. Eliminar filas con valores nulos en la variable objetivo
df = df.dropna(subset=['review_scores_communication'])

In [1314]:
# 2. Crear variable binaria: 1 si limpieza >= 4.8, 0 si < 4.8
df['communication_binaria'] = df['review_scores_communication'].apply(lambda x: 1 if x >= 4.8 else 0).astype(int)

In [1315]:
# 3. Definir variables independientes y dependiente
Vars_Indep = df[['host_response_rate','number_of_reviews','price']]
Var_dep = df['cleanliness_binaria']  # ¡¡¡Esto es CLAVE!!!

In [1316]:
# 4. One-hot encoding
X = pd.get_dummies(Vars_Indep, drop_first=True)

In [1317]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Var_dep, test_size=0.3, random_state=42)

In [1318]:
escalar = StandardScaler()

In [1319]:
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

In [1320]:
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression(class_weight='balanced')
algoritmo.fit(X_train, y_train)

LogisticRegression(class_weight='balanced')

In [1321]:
y_pred = algoritmo.predict(X_test)
y_pred

array([0, 1, 0, ..., 0, 0, 1])

In [1322]:
#Matriz de confusión
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred)
print(matriz)

[[10950  7562]
 [ 4348  5779]]


In [1323]:
from sklearn.metrics import precision_score
precision = precision_score(y_test, y_pred, average="binary", pos_label=1)
print('precision: ',precision)

precision:  0.43317592384378983


In [1324]:
from sklearn.metrics import accuracy_score
exactitud = accuracy_score(y_test, y_pred)  
print("exactitud: ",exactitud)

exactitud:  0.584133524215231


In [1325]:
from sklearn.metrics import recall_score
sensibilidad = recall_score(y_test, y_pred, average="binary", pos_label=1)
print("Sensibilidad del modelo:")
print("sensibilidad: ",sensibilidad)

Sensibilidad del modelo:
sensibilidad:  0.5706527105756888


**Regresión logistica "Accommodates"**

In [1326]:
# 1. Eliminar filas con valores nulos en la variable objetivo
df = df.dropna(subset=['accommodates'])

In [1327]:
# 2. Crear variable binaria: 1 si limpieza >= 3, 0 si < 3
df['accommodates_binaria'] = df['accommodates'].apply(lambda x: 1 if x >= 3 else 0).astype(int)

In [1328]:
# 3. Definir variables independientes y dependiente
Vars_Indep = df[['bathrooms','price','beds']]
Var_dep = df['accommodates_binaria']  

In [1329]:
# 4. One-hot encoding
X = pd.get_dummies(Vars_Indep, drop_first=True)

In [1330]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Var_dep, test_size=0.3, random_state=42)

In [1331]:
escalar = StandardScaler()

In [1332]:
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

In [1333]:
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression(class_weight='balanced')
algoritmo.fit(X_train, y_train)

LogisticRegression(class_weight='balanced')

In [1334]:
y_pred = algoritmo.predict(X_test)
y_pred

array([0, 0, 1, ..., 1, 1, 0])

In [1335]:
#Matriz de confusión
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred)
print(matriz)

[[ 7953  5994]
 [ 1583 13109]]


In [1336]:
from sklearn.metrics import precision_score
precision = precision_score(y_test, y_pred, average="binary", pos_label=1)
print('precision: ',precision)

precision:  0.6862272941422813


In [1337]:
from sklearn.metrics import accuracy_score
exactitud = accuracy_score(y_test, y_pred)  
print("exactitud: ",exactitud)

exactitud:  0.7354307063794127


In [1338]:
from sklearn.metrics import recall_score
sensibilidad = recall_score(y_test, y_pred, average="binary", pos_label=1)
print("Sensibilidad del modelo:")
print("sensibilidad: ",sensibilidad)

Sensibilidad del modelo:
sensibilidad:  0.8922542880479173


**Regresión logistica "minimum_nights"**

In [1339]:
# 1. Eliminar filas con valores nulos en la variable objetivo
df = df.dropna(subset=['minimum_nights'])

In [1340]:
# 2. Crear variable binaria: 1 si limpieza >= 4.8, 0 si < 4.8
df['minimum_binaria'] = df['minimum_nights'].apply(lambda x: 1 if x >= 2 else 0).astype(int)

In [1341]:
# 3. Definir variables independientes y dependiente
Vars_Indep = df[['price','number_of_reviews','accommodates']]
Var_dep = df['minimum_binaria']  

In [1342]:
# 4. One-hot encoding
X = pd.get_dummies(Vars_Indep, drop_first=True)

In [1343]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Var_dep, test_size=0.3, random_state=42)

In [1344]:
escalar = StandardScaler()

In [1345]:
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

In [1346]:
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression(class_weight='balanced')
algoritmo.fit(X_train, y_train)

LogisticRegression(class_weight='balanced')

In [1347]:
y_pred = algoritmo.predict(X_test)
y_pred

array([0, 1, 1, ..., 1, 1, 1])

In [1348]:
#Matriz de confusión
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred)
print(matriz)

[[ 2852  4075]
 [ 9024 12688]]


In [1349]:
from sklearn.metrics import precision_score
precision = precision_score(y_test, y_pred, average="binary", pos_label=1)
print('precision: ',precision)

precision:  0.7569050885879616


In [1350]:
from sklearn.metrics import accuracy_score
exactitud = accuracy_score(y_test, y_pred)  
print("exactitud: ",exactitud)

exactitud:  0.542616711477356


In [1351]:
from sklearn.metrics import recall_score
sensibilidad = recall_score(y_test, y_pred, average="binary", pos_label=1)
print("Sensibilidad del modelo:")
print("sensibilidad: ",sensibilidad)

Sensibilidad del modelo:
sensibilidad:  0.5843773028739867
