In [156]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import scipy.special as special
import scipy.optimize as optimize
import seaborn as sns
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [157]:
df = pd.read_csv('Tasmania_datos_limpios.csv')
df.head(2)

Unnamed: 0                         listing_url last_scraped  \
0           0  https://www.airbnb.com/rooms/35644   2024-09-05   
1           1  https://www.airbnb.com/rooms/84581   2024-09-05   

                                         description  \
0  This renovated 1885 house has fantastic views ...   
1  Kentisbury Country House is a gorgeous, self c...   

                                   host_url  host_since host_response_time  \
0  https://www.airbnb.com/users/show/153268  2010-06-27     within an hour   
1  https://www.airbnb.com/users/show/461471  2011-03-24     within an hour   

  host_response_rate host_acceptance_rate host_is_superhost  ...  \
0               100%                  98%                 t  ...   
1               100%                 100%                 t  ...   

  review_scores_accuracy review_scores_cleanliness review_scores_checkin  \
0                   4.87                      4.82                  4.96   
1                   4.96                      4.99                  4.98   

  review_scores_communication review_scores_location  \
0                        4.96                   4.81   
1                        4.98                   4.90   

  calculated_host_listings_count calculated_host_listings_count_entire_homes  \
0                            3.0                                         2.0   
1                            1.0                                         1.0   

  calculated_host_listings_count_private_rooms  \
0                                          0.0   
1                                          0.0   

  calculated_host_listings_count_shared_rooms reviews_per_month  
0                                         0.0              1.78  
1                                         0.0              1.27  

[2 rows x 51 columns]

**Regresión logistica "host is superhost"**

In [158]:
Vars_Indep = df[['price','host_total_listings_count','review_scores_communication']]
Var_dep = df['host_is_superhost']

In [159]:
X = Vars_Indep
Y = Var_dep

In [160]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.3, random_state=None)

In [161]:
escalar = StandardScaler()

In [162]:
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

In [163]:
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression()
algoritmo.fit(X_train, y_train)

LogisticRegression()

In [164]:
y_pred = algoritmo.predict(X_test)
y_pred

array(['t', 't', 't', ..., 't', 't', 't'], shape=(1869,), dtype=object)

In [165]:
#Matriz de confusión
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred)
print(matriz)

[[   7  839]
 [  12 1011]]


In [166]:
from sklearn.metrics import precision_score
precision = precision_score(y_test, y_pred, average="binary", pos_label="f")
print('precision: ',precision)

precision:  0.3684210526315789


In [167]:
from sklearn.metrics import accuracy_score
exactitud = accuracy_score(y_test, y_pred)  
print("exatitud: ",exactitud)

exatitud:  0.5446762974852862


In [168]:
from sklearn.metrics import recall_score
sensibilidad = recall_score(y_test, y_pred, average="binary", pos_label="f")
print("Sensibilidad del modelo:")
print("sensibilidad: ",sensibilidad)

Sensibilidad del modelo:
sensibilidad:  0.008274231678486997


**Regresión logistica "instant_bookable"**

In [169]:
unico = np.unique(df['instant_bookable'])
unico

array(['f', 't'], dtype=object)

In [170]:
Vars_Indep = df[['number_of_reviews','host_total_listings_count','review_scores_checkin']]
Var_dep = df['instant_bookable']

In [171]:
X = Vars_Indep
Y = Var_dep

In [172]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.3, random_state=None)

In [173]:
escalar = StandardScaler()

In [174]:
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

In [175]:
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression()
algoritmo.fit(X_train, y_train)

LogisticRegression()

In [176]:
y_pred = algoritmo.predict(X_test)
y_pred

array(['t', 't', 'f', ..., 'f', 'f', 't'], shape=(1869,), dtype=object)

In [177]:
#Matriz de confusión
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred)
print(matriz)

[[599 305]
 [379 586]]


In [178]:
from sklearn.metrics import precision_score
precision = precision_score(y_test, y_pred, average="binary", pos_label="f")
print('precision: ',precision)

precision:  0.6124744376278118


In [179]:
from sklearn.metrics import accuracy_score
exactitud = accuracy_score(y_test, y_pred)  
print("exatitud: ",exactitud)

exatitud:  0.6340288924558587


In [180]:
from sklearn.metrics import recall_score
sensibilidad = recall_score(y_test, y_pred, average="binary", pos_label="f")
print("sensibilidad: ",sensibilidad)

sensibilidad:  0.6626106194690266


**Regresión logistica "host_response_time"**

In [181]:
unico = np.unique(df['host_response_time'])
unico

array(['No hay tiempo de respuesta', 'a few days or more', 'within a day',
       'within a few hours', 'within an hour'], dtype=object)

In [182]:
df['host_response_time'] = df['host_response_time'].replace(['a few days or more','within a day', 'within a few hours','No hay tiempo de respuesta'],'NO within an hour')

In [183]:
Vars_Indep = df[['number_of_reviews','host_total_listings_count','review_scores_communication']]
Var_dep = df['host_response_time']

In [184]:
X = Vars_Indep
Y = Var_dep
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.3, random_state=None)
escalar = StandardScaler()

In [185]:
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

In [186]:
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression()
algoritmo.fit(X_train, y_train)

LogisticRegression()

In [187]:
y_pred = algoritmo.predict(X_test)
y_pred

array(['within an hour', 'within an hour', 'within an hour', ...,
       'within an hour', 'within an hour', 'within an hour'],
      shape=(1869,), dtype=object)

In [188]:
#Matriz de confusión
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred)
print(matriz)

[[   0  447]
 [   0 1422]]


In [189]:
from sklearn.metrics import precision_score
precision = precision_score(y_test, y_pred, average="binary", pos_label="within an hour")
print('precision: ',precision)

precision:  0.7608346709470305


In [190]:
from sklearn.metrics import accuracy_score
exactitud = accuracy_score(y_test, y_pred)  
print("exatitud: ",exactitud)

exatitud:  0.7608346709470305


In [191]:
from sklearn.metrics import recall_score
sensibilidad = recall_score(y_test, y_pred, average="binary", pos_label="within an hour")
print("sensibilidad: ",sensibilidad)

sensibilidad:  1.0


**Regresión logistica "room_type"**

In [192]:
unico = np.unique(df['room_type'])
unico

array(['Entire home/apt', 'Hotel room', 'Private room', 'Shared room'],
      dtype=object)

In [193]:
df['room_type'] = df['room_type'].replace(['Entire home/apt','Hotel room', 'Shared room'],'NO Private room')

In [194]:
Vars_Indep = df[['bedrooms','price','beds']]
Var_dep = df['room_type']

In [195]:
X = Vars_Indep
Y = Var_dep
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.3, random_state=None)
escalar = StandardScaler()

In [196]:
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

In [197]:
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression()
algoritmo.fit(X_train, y_train)

LogisticRegression()

In [198]:
y_pred = algoritmo.predict(X_test)
y_pred

array(['NO Private room', 'NO Private room', 'NO Private room', ...,
       'NO Private room', 'NO Private room', 'Private room'],
      shape=(1869,), dtype=object)

In [199]:
#Matriz de confusión
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred)
print(matriz)

[[1624   36]
 [ 203    6]]


In [200]:
from sklearn.metrics import precision_score
precision = precision_score(y_test, y_pred, average="binary", pos_label="Private room")
print('precision: ',precision)

precision:  0.14285714285714285


In [201]:
from sklearn.metrics import accuracy_score
exactitud = accuracy_score(y_test, y_pred)  
print("exatitud: ",exactitud)

exatitud:  0.8721241305510968


In [202]:
from sklearn.metrics import recall_score
sensibilidad = recall_score(y_test, y_pred, average="binary", pos_label="Private room")
print("sensibilidad: ",sensibilidad)

sensibilidad:  0.028708133971291867


**Regresión logistica "review_scores cleanliness"**

In [203]:
# 1. Eliminar filas con valores nulos en la variable objetivo
df = df.dropna(subset=['review_scores_cleanliness'])

In [204]:
# 2. Crear variable binaria: 1 si limpieza >= 4.8, 0 si < 4.8
df['cleanliness_binaria'] = df['review_scores_cleanliness'].apply(lambda x: 1 if x >= 4.8 else 0).astype(int)

In [205]:
# 3. Definir variables independientes y dependiente
Vars_Indep = df[['room_type','price','host_is_superhost']]
Var_dep = df['cleanliness_binaria']  # ¡¡¡Esto es CLAVE!!!

In [206]:
# 4. One-hot encoding
X = pd.get_dummies(Vars_Indep, drop_first=True)

In [207]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Var_dep, test_size=0.3, random_state=42)

In [208]:
escalar = StandardScaler()

In [209]:
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

In [210]:
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression(class_weight='balanced')
algoritmo.fit(X_train, y_train)

LogisticRegression(class_weight='balanced')

In [211]:
y_pred = algoritmo.predict(X_test)
y_pred

array([1, 1, 1, ..., 0, 1, 0], shape=(1869,))

In [212]:
#Matriz de confusión
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred)
print(matriz)

[[  83   75]
 [ 626 1085]]


In [213]:
from sklearn.metrics import precision_score
precision = precision_score(y_test, y_pred, average="binary", pos_label=1)
print('precision: ',precision)

precision:  0.9353448275862069


In [214]:
from sklearn.metrics import accuracy_score
exactitud = accuracy_score(y_test, y_pred)  
print("exactitud: ",exactitud)

exactitud:  0.6249331193151418


In [215]:
from sklearn.metrics import recall_score
sensibilidad = recall_score(y_test, y_pred, average="binary", pos_label=1)
print("Sensibilidad del modelo:")
print("sensibilidad: ",sensibilidad)

Sensibilidad del modelo:
sensibilidad:  0.6341320864991233


**Regresión logistica "host_identity_verified"**

In [216]:
Vars_Indep = df[['price','number_of_reviews','review_scores_communication']]
Var_dep = df['host_identity_verified']

In [217]:
X = Vars_Indep
Y = Var_dep

In [218]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.3, random_state=None)

In [219]:
escalar = StandardScaler()

In [220]:
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

In [221]:
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression(class_weight='balanced')
algoritmo.fit(X_train, y_train)

LogisticRegression(class_weight='balanced')

In [222]:
y_pred = algoritmo.predict(X_test)
y_pred

array(['t', 't', 'f', ..., 't', 'f', 'f'], shape=(1869,), dtype=object)

In [223]:
#Matriz de confusión
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred)
print(matriz)

[[ 67  30]
 [837 935]]


In [224]:
from sklearn.metrics import precision_score
precision = precision_score(y_test, y_pred, average="binary", pos_label="f")
print('precision: ',precision)

precision:  0.07411504424778761


In [225]:
from sklearn.metrics import accuracy_score
exactitud = accuracy_score(y_test, y_pred)  
print("exatitud: ",exactitud)

exatitud:  0.536115569823435


In [226]:
from sklearn.metrics import recall_score
sensibilidad = recall_score(y_test, y_pred, average="binary", pos_label="f")
print("Sensibilidad del modelo:")
print("sensibilidad: ",sensibilidad)

Sensibilidad del modelo:
sensibilidad:  0.6907216494845361


**Regresión logistica "has_availability"**

In [227]:
Vars_Indep = df[['number_of_reviews','host_total_listings_count','review_scores_checkin']]
Var_dep = df['has_availability']

In [228]:
X = Vars_Indep
Y = Var_dep

In [229]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.3, random_state=None)

In [230]:
escalar = StandardScaler()

In [231]:
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

In [232]:
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression(class_weight='balanced')
algoritmo.fit(X_train, y_train)

LogisticRegression(class_weight='balanced')

In [233]:
y_pred = algoritmo.predict(X_test)
y_pred

array(['f', 't', 't', ..., 't', 't', 'f'], shape=(1869,), dtype=object)

In [234]:
#Matriz de confusión
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred)
print(matriz)

[[  11    4]
 [ 618 1236]]


In [235]:
from sklearn.metrics import precision_score
precision = precision_score(y_test, y_pred, average="binary", pos_label="f")
print('precision: ',precision)

precision:  0.017488076311605722


In [236]:
from sklearn.metrics import accuracy_score
exactitud = accuracy_score(y_test, y_pred)  
print("exatitud: ",exactitud)

exatitud:  0.6672017121455324


In [237]:
from sklearn.metrics import recall_score
sensibilidad = recall_score(y_test, y_pred, average="binary", pos_label="f")
print("Sensibilidad del modelo:")
print("sensibilidad: ",sensibilidad)

Sensibilidad del modelo:
sensibilidad:  0.7333333333333333


**Regresión logistica "review_scores_communication"**

In [238]:
# 1. Eliminar filas con valores nulos en la variable objetivo
df = df.dropna(subset=['review_scores_communication'])

In [239]:
# 2. Crear variable binaria: 1 si limpieza >= 4.8, 0 si < 4.8
df['communication_binaria'] = df['review_scores_communication'].apply(lambda x: 1 if x >= 4.8 else 0).astype(int)

In [240]:
# 3. Definir variables independientes y dependiente
Vars_Indep = df[['host_response_rate','number_of_reviews','price']]
Var_dep = df['cleanliness_binaria']  # ¡¡¡Esto es CLAVE!!!

In [241]:
# 4. One-hot encoding
X = pd.get_dummies(Vars_Indep, drop_first=True)

In [242]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Var_dep, test_size=0.3, random_state=42)

In [243]:
escalar = StandardScaler()

In [244]:
escalar = StandardScaler()

In [245]:
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

In [246]:
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression(class_weight='balanced')
algoritmo.fit(X_train, y_train)

LogisticRegression(class_weight='balanced')

In [247]:
y_pred = algoritmo.predict(X_test)
y_pred

array([1, 0, 0, ..., 0, 1, 1], shape=(1869,))

In [248]:
#Matriz de confusión
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred)
print(matriz)

[[  69   89]
 [ 562 1149]]


In [249]:
from sklearn.metrics import precision_score
precision = precision_score(y_test, y_pred, average="binary", pos_label=1)
print('precision: ',precision)

precision:  0.9281098546042004


In [250]:
from sklearn.metrics import accuracy_score
exactitud = accuracy_score(y_test, y_pred)  
print("exactitud: ",exactitud)

exactitud:  0.651685393258427


In [251]:
from sklearn.metrics import recall_score
sensibilidad = recall_score(y_test, y_pred, average="binary", pos_label=1)
print("Sensibilidad del modelo:")
print("sensibilidad: ",sensibilidad)

Sensibilidad del modelo:
sensibilidad:  0.6715371127995324


**Regresión logistica "Accommodates"**

In [252]:
# 1. Eliminar filas con valores nulos en la variable objetivo
df = df.dropna(subset=['accommodates'])

In [253]:
# 2. Crear variable binaria: 1 si limpieza >= 3, 0 si < 3
df['accommodates_binaria'] = df['accommodates'].apply(lambda x: 1 if x >= 3 else 0).astype(int)

In [254]:
# 3. Definir variables independientes y dependiente
Vars_Indep = df[['bathrooms','price','beds']]
Var_dep = df['accommodates_binaria']  

In [255]:
# 4. One-hot encoding
X = pd.get_dummies(Vars_Indep, drop_first=True)

In [256]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Var_dep, test_size=0.3, random_state=42)

In [257]:
escalar = StandardScaler()

In [258]:
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

In [259]:
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression(class_weight='balanced')
algoritmo.fit(X_train, y_train)

LogisticRegression(class_weight='balanced')

In [260]:
y_pred = algoritmo.predict(X_test)
y_pred

array([1, 1, 1, ..., 0, 0, 1], shape=(1869,))

In [261]:
#Matriz de confusión
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred)
print(matriz)

[[ 446  108]
 [ 277 1038]]


In [262]:
from sklearn.metrics import precision_score
precision = precision_score(y_test, y_pred, average="binary", pos_label=1)
print('precision: ',precision)

precision:  0.9057591623036649


In [263]:
from sklearn.metrics import accuracy_score
exactitud = accuracy_score(y_test, y_pred)  
print("exactitud: ",exactitud)

exactitud:  0.7940074906367042


In [264]:
from sklearn.metrics import recall_score
sensibilidad = recall_score(y_test, y_pred, average="binary", pos_label=1)
print("Sensibilidad del modelo:")
print("sensibilidad: ",sensibilidad)

Sensibilidad del modelo:
sensibilidad:  0.7893536121673004


**Regresión logistica "minimum_nights"**

In [265]:
# 1. Eliminar filas con valores nulos en la variable objetivo
df = df.dropna(subset=['minimum_nights'])

In [266]:
# 2. Crear variable binaria: 1 si limpieza >= 4.8, 0 si < 4.8
df['minimum_binaria'] = df['minimum_nights'].apply(lambda x: 1 if x >= 2 else 0).astype(int)

In [267]:
# 3. Definir variables independientes y dependiente
Vars_Indep = df[['price','number_of_reviews','accommodates']]
Var_dep = df['minimum_binaria']  

In [268]:
# 4. One-hot encoding
X = pd.get_dummies(Vars_Indep, drop_first=True)

In [269]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Var_dep, test_size=0.3, random_state=42)

In [270]:
escalar = StandardScaler()

In [271]:
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

In [272]:
print(df['minimum_binaria'].value_counts())


minimum_binaria
1    3719
0    2511
Name: count, dtype: int64


In [273]:
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression(class_weight='balanced')
algoritmo.fit(X_train, y_train)

LogisticRegression(class_weight='balanced')

In [274]:
y_pred = algoritmo.predict(X_test)
y_pred

array([0, 1, 1, ..., 0, 0, 1], shape=(1869,))

In [275]:
#Matriz de confusión
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred)
print(matriz)

[[471 268]
 [519 611]]


In [276]:
from sklearn.metrics import precision_score
precision = precision_score(y_test, y_pred, average="binary", pos_label=1)
print('precision: ',precision)

precision:  0.6951080773606371


In [277]:
from sklearn.metrics import accuracy_score
exactitud = accuracy_score(y_test, y_pred)  
print("exactitud: ",exactitud)

exactitud:  0.5789192081326913


In [278]:
from sklearn.metrics import recall_score
sensibilidad = recall_score(y_test, y_pred, average="binary", pos_label=1)
print("Sensibilidad del modelo:")
print("sensibilidad: ",sensibilidad)

Sensibilidad del modelo:
sensibilidad:  0.54070796460177
