In [343]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import scipy.special as special
import scipy.optimize as optimize
import seaborn as sns
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [344]:
df = pd.read_csv('Mexico_datos_limpios.csv')
df.head(2)

Unnamed: 0                         listing_url last_scraped  \
0           0  https://www.airbnb.com/rooms/35797   2024-09-25   
1           1  https://www.airbnb.com/rooms/44616   2024-09-26   

                                         description  \
0  Dentro de Villa un estudio de arte con futon, ...   
1  A new concept of hosting in mexico through a b...   

                                   host_url  host_since  host_response_time  \
0  https://www.airbnb.com/users/show/153786  2010-06-28  a few days or more   
1  https://www.airbnb.com/users/show/196253  2010-08-09      within an hour   

  host_response_rate              host_acceptance_rate host_is_superhost  ...  \
0                 0%  No contiene host_acceptance_rate                 f  ...   
1               100%                               93%                 t  ...   

  review_scores_accuracy review_scores_cleanliness review_scores_checkin  \
0                   4.79                      4.76                  4.84   
1                   4.88                      4.70                  4.87   

  review_scores_communication review_scores_location  \
0                        4.83                   4.85   
1                        4.78                   4.98   

  calculated_host_listings_count calculated_host_listings_count_entire_homes  \
0                            1.0                                         1.0   
1                            8.0                                         4.0   

  calculated_host_listings_count_private_rooms  \
0                                          0.0   
1                                          1.0   

  calculated_host_listings_count_shared_rooms reviews_per_month  
0                                         0.0              1.74  
1                                         0.0              0.41  

[2 rows x 51 columns]

**Regresión logistica "host is superhost"**

In [345]:
Vars_Indep = df[['price','host_total_listings_count','review_scores_communication']]
Var_dep = df['host_is_superhost']

In [346]:
X = Vars_Indep
Y = Var_dep

In [347]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.3, random_state=None)

In [348]:
escalar = StandardScaler()

In [349]:
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

In [350]:
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression()
algoritmo.fit(X_train, y_train)

LogisticRegression()

In [351]:
y_pred = algoritmo.predict(X_test)
y_pred

array(['t', 'f', 'f', ..., 'f', 'f', 't'], dtype=object)

In [352]:
#Matriz de confusión
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred)
print(matriz)

[[3701  906]
 [2254 1114]]


In [353]:
from sklearn.metrics import precision_score
precision = precision_score(y_test, y_pred, average="binary", pos_label="f")
print('precision: ',precision)

precision:  0.6214945424013434


In [354]:
from sklearn.metrics import accuracy_score
exactitud = accuracy_score(y_test, y_pred)  
print("exatitud: ",exactitud)

exatitud:  0.6037617554858934


In [355]:
from sklearn.metrics import recall_score
sensibilidad = recall_score(y_test, y_pred, average="binary", pos_label="f")
print("Sensibilidad del modelo:")
print("sensibilidad: ",sensibilidad)

Sensibilidad del modelo:
sensibilidad:  0.8033427393097461


**Regresión logistica "instant_bookable"**

In [356]:
unico = np.unique(df['instant_bookable'])
unico

array(['f', 't'], dtype=object)

In [357]:
Vars_Indep = df[['number_of_reviews','host_total_listings_count','review_scores_checkin']]
Var_dep = df['instant_bookable']

In [358]:
X = Vars_Indep
Y = Var_dep

In [359]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.3, random_state=None)

In [360]:
escalar = StandardScaler()

In [361]:
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

In [362]:
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression()
algoritmo.fit(X_train, y_train)

LogisticRegression()

In [363]:
y_pred = algoritmo.predict(X_test)
y_pred

array(['f', 'f', 'f', ..., 'f', 'f', 'f'], dtype=object)

In [364]:
#Matriz de confusión
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred)
print(matriz)

[[4321  502]
 [2511  641]]


In [365]:
from sklearn.metrics import precision_score
precision = precision_score(y_test, y_pred, average="binary", pos_label="f")
print('precision: ',precision)

precision:  0.6324648711943794


In [366]:
from sklearn.metrics import accuracy_score
exactitud = accuracy_score(y_test, y_pred)  
print("exatitud: ",exactitud)

exatitud:  0.6221943573667712


In [367]:
from sklearn.metrics import recall_score
sensibilidad = recall_score(y_test, y_pred, average="binary", pos_label="f")
print("sensibilidad: ",sensibilidad)

sensibilidad:  0.8959154053493676


**Regresión logistica "host_response_time"**

In [368]:
unico = np.unique(df['host_response_time'])
unico

array(['a few days or more', 'within a day', 'within a few hours',
       'within an hour'], dtype=object)

In [369]:
df['host_response_time'] = df['host_response_time'].replace(['a few days or more','within a day', 'within a few hours'],'NO within an hour')

In [370]:
Vars_Indep = df[['number_of_reviews','host_total_listings_count','review_scores_communication']]
Var_dep = df['host_response_time']

In [371]:
X = Vars_Indep
Y = Var_dep
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.3, random_state=None)
escalar = StandardScaler()

In [372]:
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

In [373]:
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression()
algoritmo.fit(X_train, y_train)

LogisticRegression()

In [374]:
y_pred = algoritmo.predict(X_test)
y_pred

array(['within an hour', 'within an hour', 'within an hour', ...,
       'within an hour', 'within an hour', 'within an hour'], dtype=object)

In [375]:
#Matriz de confusión
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred)
print(matriz)

[[   0 1268]
 [   0 6707]]


In [376]:
from sklearn.metrics import precision_score
precision = precision_score(y_test, y_pred, average="binary", pos_label="within an hour")
print('precision: ',precision)

precision:  0.8410031347962382


In [377]:
from sklearn.metrics import accuracy_score
exactitud = accuracy_score(y_test, y_pred)  
print("exatitud: ",exactitud)

exatitud:  0.8410031347962382


In [378]:
from sklearn.metrics import recall_score
sensibilidad = recall_score(y_test, y_pred, average="binary", pos_label="within an hour")
print("sensibilidad: ",sensibilidad)

sensibilidad:  1.0


**Regresión logistica "room_type"**

In [379]:
unico = np.unique(df['room_type'])
unico

array(['Entire home/apt', 'Hotel room', 'Private room', 'Shared room'],
      dtype=object)

In [380]:
df['room_type'] = df['room_type'].replace(['Entire home/apt','Hotel room', 'Shared room'],'NO Private room')

In [381]:
Vars_Indep = df[['bedrooms','price','beds']]
Var_dep = df['room_type']

In [382]:
X = Vars_Indep
Y = Var_dep
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.3, random_state=None)
escalar = StandardScaler()

In [383]:
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

In [384]:
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression()
algoritmo.fit(X_train, y_train)

LogisticRegression()

In [385]:
y_pred = algoritmo.predict(X_test)
y_pred

array(['NO Private room', 'NO Private room', 'NO Private room', ...,
       'Private room', 'NO Private room', 'NO Private room'], dtype=object)

In [386]:
#Matriz de confusión
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred)
print(matriz)

[[4523  815]
 [ 833 1804]]


In [387]:
from sklearn.metrics import precision_score
precision = precision_score(y_test, y_pred, average="binary", pos_label="Private room")
print('precision: ',precision)

precision:  0.6888125238640702


In [388]:
from sklearn.metrics import accuracy_score
exactitud = accuracy_score(y_test, y_pred)  
print("exatitud: ",exactitud)

exatitud:  0.7933542319749216


In [389]:
from sklearn.metrics import recall_score
sensibilidad = recall_score(y_test, y_pred, average="binary", pos_label="Private room")
print("sensibilidad: ",sensibilidad)

sensibilidad:  0.6841107318923019


**Regresión logistica "review_scores cleanliness"**

In [390]:
# 1. Eliminar filas con valores nulos en la variable objetivo
df = df.dropna(subset=['review_scores_cleanliness'])

In [391]:
# 2. Crear variable binaria: 1 si limpieza >= 4.8, 0 si < 4.8
df['cleanliness_binaria'] = df['review_scores_cleanliness'].apply(lambda x: 1 if x >= 4.8 else 0).astype(int)

In [392]:
# 3. Definir variables independientes y dependiente
Vars_Indep = df[['room_type','price','host_is_superhost']]
Var_dep = df['cleanliness_binaria']  # ¡¡¡Esto es CLAVE!!!

In [393]:
# 4. One-hot encoding
X = pd.get_dummies(Vars_Indep, drop_first=True)

In [394]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Var_dep, test_size=0.3, random_state=42)

In [395]:
escalar = StandardScaler()

In [396]:
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

In [397]:
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression(class_weight='balanced')
algoritmo.fit(X_train, y_train)

LogisticRegression(class_weight='balanced')

In [398]:
y_pred = algoritmo.predict(X_test)
y_pred

array([0, 1, 1, ..., 0, 1, 0])

In [399]:
#Matriz de confusión
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred)
print(matriz)

[[1731  698]
 [2909 2637]]


In [400]:
from sklearn.metrics import precision_score
precision = precision_score(y_test, y_pred, average="binary", pos_label=1)
print('precision: ',precision)

precision:  0.7907046476761619


In [401]:
from sklearn.metrics import accuracy_score
exactitud = accuracy_score(y_test, y_pred)  
print("exactitud: ",exactitud)

exactitud:  0.5477115987460816


In [402]:
from sklearn.metrics import recall_score
sensibilidad = recall_score(y_test, y_pred, average="binary", pos_label=1)
print("Sensibilidad del modelo:")
print("sensibilidad: ",sensibilidad)

Sensibilidad del modelo:
sensibilidad:  0.47547782185358817


**Regresión logistica "host_identity_verified"**

In [403]:
Vars_Indep = df[['price','number_of_reviews','review_scores_communication']]
Var_dep = df['host_identity_verified']

In [404]:
X = Vars_Indep
Y = Var_dep

In [405]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.3, random_state=None)

In [406]:
escalar = StandardScaler()

In [407]:
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

In [408]:
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression(class_weight='balanced')
algoritmo.fit(X_train, y_train)

LogisticRegression(class_weight='balanced')

In [409]:
y_pred = algoritmo.predict(X_test)
y_pred

array(['t', 't', 't', ..., 't', 't', 't'], dtype=object)

In [410]:
#Matriz de confusión
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred)
print(matriz)

[[ 265   77]
 [1947 5686]]


In [411]:
from sklearn.metrics import precision_score
precision = precision_score(y_test, y_pred, average="binary", pos_label="f")
print('precision: ',precision)

precision:  0.11980108499095841


In [412]:
from sklearn.metrics import accuracy_score
exactitud = accuracy_score(y_test, y_pred)  
print("exatitud: ",exactitud)

exatitud:  0.7462068965517241


In [413]:
from sklearn.metrics import recall_score
sensibilidad = recall_score(y_test, y_pred, average="binary", pos_label="f")
print("Sensibilidad del modelo:")
print("sensibilidad: ",sensibilidad)

Sensibilidad del modelo:
sensibilidad:  0.7748538011695907


**Regresión logistica "has_availability"**

In [414]:
Vars_Indep = df[['number_of_reviews','host_total_listings_count','review_scores_checkin']]
Var_dep = df['has_availability']

In [415]:
X = Vars_Indep
Y = Var_dep

In [416]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.3, random_state=None)

In [417]:
escalar = StandardScaler()

In [418]:
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

In [419]:
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression(class_weight='balanced')
algoritmo.fit(X_train, y_train)

LogisticRegression(class_weight='balanced')

In [420]:
y_pred = algoritmo.predict(X_test)
y_pred

array(['t', 't', 't', ..., 't', 'f', 't'], dtype=object)

In [421]:
#Matriz de confusión
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred)
print(matriz)

[[ 267   32]
 [1916 5760]]


In [422]:
from sklearn.metrics import precision_score
precision = precision_score(y_test, y_pred, average="binary", pos_label="f")
print('precision: ',precision)

precision:  0.12230874942739349


In [423]:
from sklearn.metrics import accuracy_score
exactitud = accuracy_score(y_test, y_pred)  
print("exatitud: ",exactitud)

exatitud:  0.7557366771159875


In [424]:
from sklearn.metrics import recall_score
sensibilidad = recall_score(y_test, y_pred, average="binary", pos_label="f")
print("Sensibilidad del modelo:")
print("sensibilidad: ",sensibilidad)

Sensibilidad del modelo:
sensibilidad:  0.8929765886287625


**Regresión logistica "review_scores_communication"**

In [425]:
# 1. Eliminar filas con valores nulos en la variable objetivo
df = df.dropna(subset=['review_scores_communication'])

In [426]:
# 2. Crear variable binaria: 1 si limpieza >= 4.8, 0 si < 4.8
df['communication_binaria'] = df['review_scores_communication'].apply(lambda x: 1 if x >= 4.8 else 0).astype(int)

In [427]:
# 3. Definir variables independientes y dependiente
Vars_Indep = df[['host_response_rate','number_of_reviews','price']]
Var_dep = df['cleanliness_binaria']  # ¡¡¡Esto es CLAVE!!!

In [428]:
# 4. One-hot encoding
X = pd.get_dummies(Vars_Indep, drop_first=True)

In [429]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Var_dep, test_size=0.3, random_state=42)

In [431]:
escalar = StandardScaler()

In [432]:
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

In [433]:
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression(class_weight='balanced')
algoritmo.fit(X_train, y_train)

LogisticRegression(class_weight='balanced')

In [434]:
y_pred = algoritmo.predict(X_test)
y_pred

array([1, 1, 1, ..., 1, 1, 0])

In [435]:
#Matriz de confusión
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred)
print(matriz)

[[ 915 1514]
 [1128 4418]]


In [436]:
from sklearn.metrics import precision_score
precision = precision_score(y_test, y_pred, average="binary", pos_label=1)
print('precision: ',precision)

precision:  0.7447741065407957


In [437]:
from sklearn.metrics import accuracy_score
exactitud = accuracy_score(y_test, y_pred)  
print("exactitud: ",exactitud)

exactitud:  0.6687147335423197


In [467]:
from sklearn.metrics import recall_score
sensibilidad = recall_score(y_test, y_pred, average="binary", pos_label=1)
print("Sensibilidad del modelo:")
print("sensibilidad: ",sensibilidad)

Sensibilidad del modelo:
sensibilidad:  0.5106926268751995


**Regresión logistica "Accommodates"**

In [439]:
# 1. Eliminar filas con valores nulos en la variable objetivo
df = df.dropna(subset=['accommodates'])

In [440]:
# 2. Crear variable binaria: 1 si limpieza >= 3, 0 si < 3
df['accommodates_binaria'] = df['accommodates'].apply(lambda x: 1 if x >= 3 else 0).astype(int)

In [441]:
# 3. Definir variables independientes y dependiente
Vars_Indep = df[['bathrooms','price','beds']]
Var_dep = df['accommodates_binaria']  

In [442]:
# 4. One-hot encoding
X = pd.get_dummies(Vars_Indep, drop_first=True)

In [443]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Var_dep, test_size=0.3, random_state=42)

In [444]:
escalar = StandardScaler()

In [445]:
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

In [446]:
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression(class_weight='balanced')
algoritmo.fit(X_train, y_train)

LogisticRegression(class_weight='balanced')

In [447]:
y_pred = algoritmo.predict(X_test)
y_pred

array([0, 0, 0, ..., 1, 0, 0])

In [448]:
#Matriz de confusión
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred)
print(matriz)

[[3839  630]
 [ 776 2730]]


In [449]:
from sklearn.metrics import precision_score
precision = precision_score(y_test, y_pred, average="binary", pos_label=1)
print('precision: ',precision)

precision:  0.8125


In [450]:
from sklearn.metrics import accuracy_score
exactitud = accuracy_score(y_test, y_pred)  
print("exactitud: ",exactitud)

exactitud:  0.8236990595611285


In [451]:
from sklearn.metrics import recall_score
sensibilidad = recall_score(y_test, y_pred, average="binary", pos_label=1)
print("Sensibilidad del modelo:")
print("sensibilidad: ",sensibilidad)

Sensibilidad del modelo:
sensibilidad:  0.7786651454649173


**Regresión logistica "minimum_nights"**

In [452]:
# 1. Eliminar filas con valores nulos en la variable objetivo
df = df.dropna(subset=['minimum_nights'])

In [453]:
# 2. Crear variable binaria: 1 si limpieza >= 4.8, 0 si < 4.8
df['minimum_binaria'] = df['minimum_nights'].apply(lambda x: 1 if x >= 2 else 0).astype(int)

In [454]:
# 3. Definir variables independientes y dependiente
Vars_Indep = df[['price','number_of_reviews','accommodates']]
Var_dep = df['minimum_binaria']  

In [455]:
# 4. One-hot encoding
X = pd.get_dummies(Vars_Indep, drop_first=True)

In [456]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Var_dep, test_size=0.3, random_state=42)

In [457]:
escalar = StandardScaler()

In [458]:
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

In [459]:
print(df['minimum_binaria'].value_counts())


minimum_binaria
0    16205
1    10377
Name: count, dtype: int64


In [460]:
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression(class_weight='balanced')
algoritmo.fit(X_train, y_train)

LogisticRegression(class_weight='balanced')

In [461]:
y_pred = algoritmo.predict(X_test)
y_pred

array([0, 0, 1, ..., 0, 1, 0])

In [462]:
#Matriz de confusión
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred)
print(matriz)

[[3052 1790]
 [1533 1600]]


In [463]:
from sklearn.metrics import precision_score
precision = precision_score(y_test, y_pred, average="binary", pos_label=1)
print('precision: ',precision)

precision:  0.471976401179941


In [464]:
from sklearn.metrics import accuracy_score
exactitud = accuracy_score(y_test, y_pred)  
print("exactitud: ",exactitud)

exactitud:  0.5833228840125392


In [465]:
from sklearn.metrics import recall_score
sensibilidad = recall_score(y_test, y_pred, average="binary", pos_label=1)
print("Sensibilidad del modelo:")
print("sensibilidad: ",sensibilidad)

Sensibilidad del modelo:
sensibilidad:  0.5106926268751995
